---
- name: (CentOS) Add Microsoft repository
  ansible.builtin.yum:
    name: https://packages.microsoft.com/config/centos/{{ ansible_distribution_major_version }}/packages-microsoft-prod.rpm
    disable_gpg_check: true
    state: present
  when: ansible_distribution == 'CentOS'
  tags: install

- name: (RHEL) Add Microsoft repository
  ansible.builtin.yum_repository:
    name: "packages-microsoft-com-prod"
    description: "Microsoft repository"
    baseurl: https://packages.microsoft.com/rhel/{{ ansible_distribution_major_version }}/prod/
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  notify: yum-clean-metadata
  when: ansible_distribution == 'Red Hat Enterprise Linux'
  tags: install

- name: (RHEL/CentOS) Install sysmonforlinux package
  ansible.builtin.yum:
    name: sysmonforlinux
    state: present
  when: ansible_os_family == "RedHat"
  tags: install
