- name: Restart-sysmon
  ansible.windows.win_shell: Restart-Service sysmon

- name: Restart-sysmon64
  ansible.windows.win_shell: Restart-Service sysmon64

- name: Reload-sysmon
  ansible.windows.win_command: "\"{{ sysmon_install_path }}\\Sysmon.exe\" -c \"{{ sysmon_install_path }}\"\\sysmonconfig.xml"
  args:
    chdir: "{{ sysmon_install_path }}"

- name: Reload-sysmon64
  ansible.windows.win_command: "\"{{ sysmon_install_path }}\\Sysmon64.exe\" -c \"{{ sysmon_install_path }}\"\\sysmonconfig.xml"
  args:
    chdir: "{{ sysmon_install_path }}"

- name: Reload-linux-sysmon
  ansible.builtin.command:
    cmd: sysmon -c /etc/sysmon/config.xml
